[project]
org-name= "duneesha"
version= "0.1.0"

[dependencies]
[platform]
target = "java8"

[[platform.libraries]]
artifactId = "mysql-connector-java"
version = "8.0.19"
path = "mysqlconnectorfolder/mysql-connector-java-8.0.19.jar"
groupId = "mysql"
modules= ["mockingServiceAirline","mockingServiceHotel","mockingServiceCar"]

[build-options]
observability-included=true


